### ISSUE TITLE
Connection can't be reestablished 

### ISSUE THREAD

**Issue by marvson** [thisbejim/Pyrebase#107]
Hi, I'm having a problem while trying to do my application tolerant to failures. When I interrupt the network connection and I connect to the network again to a firebase database using pyrebase, it seems like that it can't recover the connection, being stuck in a socket error and in a thread error.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Ferramentas\_python3\lib\site-packages\httplib2\__init__.py", line 987, in _conn_request
    conn.connect()
  File "D:\Ferramentas\_python3\lib\http\client.py", line 1252, in connect
    super().connect()
  File "D:\Ferramentas\_python3\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\Ferramentas\_python3\lib\socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "D:\Ferramentas\_python3\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Ferramentas\_python3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Ferramentas\_python3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Ferramentas\_python3\lib\site-packages\pyrebase\pyrebase.py", line 554, in start_stream
    self.sse = ClosableSSEClient(self.url, session=self.make_session(), build_headers=self.build_headers)
  File "D:\Ferramentas\_python3\lib\site-packages\pyrebase\pyrebase.py", line 516, in __init__
    super(ClosableSSEClient, self).__init__(*args, **kwargs)
  File "D:\Ferramentas\_python3\lib\site-packages\sseclient\sseclient.py", line 39, in __init__
    self._connect()
  File "D:\Ferramentas\_python3\lib\site-packages\pyrebase\pyrebase.py", line 520, in _connect
    super(ClosableSSEClient, self)._connect()
  File "D:\Ferramentas\_python3\lib\site-packages\sseclient\sseclient.py", line 44, in _connect
    headers = self.build_headers()
  File "D:\Ferramentas\_python3\lib\site-packages\pyrebase\pyrebase.py", line 252, in build_headers
    headers['Authorization'] = 'Bearer ' + self.credentials.get_access_token().access_token
  File "D:\Ferramentas\_python3\lib\site-packages\oauth2client\client.py", line 677, in get_access_token
    self.refresh(http)
  File "D:\Ferramentas\_python3\lib\site-packages\oauth2client\client.py", line 560, in refresh
    self._refresh(http.request)
  File "D:\Ferramentas\_python3\lib\site-packages\oauth2client\client.py", line 765, in _refresh
    self._do_refresh_request(http_request)
  File "D:\Ferramentas\_python3\lib\site-packages\oauth2client\client.py", line 797, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "D:\Ferramentas\_python3\lib\site-packages\httplib2\__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\Ferramentas\_python3\lib\site-packages\httplib2\__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\Ferramentas\_python3\lib\site-packages\httplib2\__init__.py", line 994, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com

After that the program freezes and I can't reconnect to the server. Is there a way to use pyrebase and reconnect always when the connection fails?

I'm using python 3.5.2 and pyrebase 3.0.24. Thanks in advance.

**Comment by devmarcocrotti** [comment]
Hi guys, I have the same kind of problem. Have you find a solution? Thaks to share your information.

**Comment by marvson** [comment]
Unfortunately, we didn't. It was a college's project
 So, since we presented it, even with this issue, we had no time to try to find a solution to fix it. Sorry.

**Comment by devmarcocrotti** [comment]
Ok, thanks for your reply. It's a great project!  Cheers.

**Comment by ConProgramming** [comment]
@devmarcocrotti Did you find a solution? Or anyone else?
