### ISSUE TITLE
'ClosableSSEClient' object has no attribute 'thread'

### ISSUE THREAD

**Issue by thisbejim** [thisbejim/Pyrebase#114]
As mentioned by [@andreask1](https://github.com/thisbejim/Pyrebase/issues/80#issuecomment-266240421).

```
Traceback (most recent call last):
  File "[...]/main.py", line 115, in <module>
    time.sleep(2)
  File "[...]/main.py", line 105, in signal_handler
    fb_stream.close()
  File "/[...]/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 570, in close
    self.sse.thread.join()
AttributeError: 'ClosableSSEClient' object has no attribute 'thread'
```

**Comment by thisbejim** [comment]
Fixed in https://github.com/thisbejim/Pyrebase/pull/122

**Comment by aligajani** [comment]
Hey @thisbejim , has #80 and #123 been fixed already?
