### ISSUE TITLE
Error closing stream

### ISSUE THREAD

**Issue by tjmille2** [thisbejim/Pyrebase#138]
I am having troubles running your Firebase stream() sample in the following

stream = db.child(str(child_name)).stream(callback)
stream.close()

line 224, in make_stream
    stream.close()
  File "C:\PROGRA~1\Miniconda3\lib\site-packages\pyrebase\pyrebase.py", line 569, in close
    self.sse.close()
  File "C:\PROGRA~1\Miniconda3\lib\site-packages\pyrebase\pyrebase.py", line 529, in close
    self.resp.raw._fp.fp.raw._sock.shutdown(socket.SHUT_RDWR)
TypeError: shutdown() takes 1 positional argument but 2 were given

**Comment by TranceCat** [comment]
I get a bit different error

 my_stream.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 569, in close
    self.sse.close()
  File "/usr/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 529, in close
    self.resp.raw._fp.fp.raw._sock.shutdown(socket.SHUT_RDWR)
AttributeError: '_fileobject' object has no attribute 'raw'

**Comment by tjmille2** [comment]
@TranceCat Pyrebase is only supported on Python 3.5+, you're using Python 2.7

**Comment by TranceCat** [comment]
Thank you! Just realised it.

**Comment by tjmille2** [comment]
Did switching to python 3.5 fix your issue? It did not for me on python 3.5.



----
Tim

**Comment by TranceCat** [comment]
Problem fixed. Tested with:
Python 3.5.3
Pyrebase-3.0.27
Python is running from docker container. Official image from Python, tag – 3.5

**Comment by ukjin1192** [comment]
Same problem occurred when I tried to close stream **on thread**.
It does not yield error if not using thread.

Environment

- OS : Ubuntu 16.04.1 LTS
- Python version : 3.5.2
- Pyrebase version : 3.0.27
- [Celery](http://docs.celeryproject.org/en/latest/index.html#) version : 4.0.2 _(I use thread here)_ 

Traceback

~~~~
File "{MY PYTHON SCRIPT}.py", line 370, in {SOME FUNCTION}
  my_stream.close()
File "/usr/local/lib/python3.5/dist-packages/pyrebase/pyrebase.py", line 569, in close
  self.sse.close()
File "/usr/local/lib/python3.5/dist-packages/pyrebase/pyrebase.py", line 530, in close
  self.resp.raw._fp.fp.raw._sock.close()
AttributeError: 'NoneType' object has no attribute 'raw'
~~~~

**Comment by codeAshu** [comment]
Use this as a fix : https://gist.github.com/codeAshu/f6384203706e989b0d38db6e0a9d11e7

**Comment by heston** [comment]
PR to add this fix to Pyrebase is here: https://github.com/thisbejim/Pyrebase/pull/248
