### ISSUE TITLE
401 after several hours

### ISSUE THREAD

**Issue by vickumar1981** [thisbejim/Pyrebase#143]
Make sure these boxes are checked before submitting your issue:

[] Check that your version of Python is 3.4+
[] Check that you are on the newest version of Pyrebase
[] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

**Comment by vickumar1981** [comment]
The service accounts work great! Thanks for the additions.

My issue is that everything works fine, but after several hours (I have a daemon process that listens for changes using the stream() method), the SSEClient tells me this
```
Exception in thread Thread-1: 
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner 
self.run() 
 File "/usr/local/lib/python2.7/threading.py", line 754, in run 
self.__target(*self.__args, **self.__kwargs) 
File "/usr/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 557, in start_stream 
for msg in self.sse: 
File "/usr/local/lib/python2.7/site-packages/sseclient/sseclient.py", line 85, in __next__ 
self._connect() 
File "/usr/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 522, in _connect 
super(ClosableSSEClient, self)._connect() 
File "/usr/local/lib/python2.7/site-packages/sseclient/sseclient.py", line 54, in _connect 
self.resp.raise_for_status() 
File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status 
raise HTTPError(http_error_msg, response=self) 
HTTPError: 401 Client Error: Unauthorized for url: https://s-usc1c-nss-113.firebaseio.com/.json?ns=licensepass-98188&sse=true 
```

Happens after about 4-5 hours.  I think it's trying to reconnect and not being able too.  Any help is much appreciated.

**Comment by thisbejim** [comment]
Hi @vickumar1981, thanks for opening this issue! This is probably related to https://github.com/thisbejim/Pyrebase/issues/117 and at some point I'll have to migrate the library to google-auth.
