### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by mrchowmein** [thisbejim/Pyrebase#147]
Make sure these boxes are checked before submitting your issue:

[3.4.2] Check that your version of Python is 3.4+
[3.0.27] Check that you are on the newest version of Pyrebase
[enabled] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

The following code is throwing the error 400 below
user = auth.sign_in_with_email_and_password("secret", "secret")

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyrebase/pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=secret

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/pythonprojects/gyrotest.py", line 19, in <module>
    user = auth.sign_in_with_email_and_password("jason@test1.com", "jasonchan")
  File "/usr/local/lib/python3.4/dist-packages/pyrebase/pyrebase.py", line 85, in sign_in_with_email_and_password
    raise_detailed_error(request_object)
  File "/usr/local/lib/python3.4/dist-packages/pyrebase/pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=secret] {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "keyInvalid",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}

**Comment by mrchowmein** [comment]
i got it fix, i reentered the api key from the console. maybe it was my typo or i think firebase was having log in issues a few days ago.

**Comment by thisbejim** [comment]
Nice one @mrchowmein, glad you found a solution for this.

**Comment by ubihacks** [comment]
@mrchowmein  bro can you send me the sample code i  have same issue in uploading Image
