### ISSUE TITLE
Stream thread exception handling

### ISSUE THREAD

**Issue by anshul35** [thisbejim/Pyrebase#151]
The ```stream``` method creates a thread and if there is an error in connection to firebase, there is no way to catch that exception.

Please let me know if you guys know a fix for this.

**Comment by dauledk** [comment]
I came to Issues to open a new one - regarding exactly this problem!

I am running the Pyrebase code on a Raspberry Pi, and using supervisor to monitor the process. However the program does not work after the stream method creates the following error (from stderr.out). 

Is it the same error? 

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pyrebase/pyrebase.py", line 556, in start_stream
    self.sse = ClosableSSEClient(self.url, session=self.make_session(), build_headers=self.build_headers)
  File "/usr/local/lib/python3.4/dist-packages/pyrebase/pyrebase.py", line 518, in __init__
    super(ClosableSSEClient, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sseclient/sseclient.py", line 39, in __init__
    self._connect()
  File "/usr/local/lib/python3.4/dist-packages/pyrebase/pyrebase.py", line 522, in _connect
    super(ClosableSSEClient, self)._connect()
  File "/usr/local/lib/python3.4/dist-packages/sseclient/sseclient.py", line 54, in _connect
    self.resp.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://s-usc1c-nss-132.firebaseio.com/Settings/sound/skaale_pi.json?ns=jc-admin&sse=true`

Would be super awesome with a solution to this, as of right now I'm manually restarting the program when this error occurs.

**Comment by dauledk** [comment]
No fix or workaround for this issue?

**Comment by mcarrilloco** [comment]
I just came around this issue myself, after a few hours the stream dies for different reasons (probably a 500 or related error). I think we have two different issues. First one is catching the exception. What I'm doing in my code right now is doing a subclass of `Stream` (and `Database` and `Firebase`) so the stream call can receive a function that wraps the `start_stream` method in a try/except block. In our case we send the report to Sentry. If this is something the library would like to support I can make a pull request and discuss around that.

The second problem is to actually monitor the threads and restart them in case of exception. In this case the `stream` function returns a `Stream` object, this object has the `thread` that is running as an attribute. A basic solution is to ping the `is_active` method actively and restart the stream if it has been stopped. I think this is more specific for each application but the library could be more friendly helping the developer around it.

I'll give it a few days and if it looks that the solutions in place are holding I'll attempt to make a Pull Request. For now this is what it has been working for me.

**Comment by dauledk** [comment]
@mcarrilloco sounds awesome. So basically you could just make a while loop checking the is_active method - and restart the thread if false? 

Do you mind sharing the code describing how you catch the exception?

**Comment by mcarrilloco** [comment]
No problem @dauledk. Yes on the while loop. This is more or less what I'm doing:

```
def start_parent_stream():
    return db.child("<child to listen>").stream(stream_handler=stream_handler)


def listen_firebase_for_new_messages():
    parent_stream = start_parent_stream()
    while True:
        time.sleep(0.5)
        if not parent_stream.thread.is_alive():
            try:
                parent_stream.close()
            except Exception:
                client.captureException(tags={'handled_status': 'catched_and_logged'})
            parent_stream = start_parent_stream()
```

And to catch the exception I am basically maintaining a module that subclases several of the components of the core Pyrebase. In this case I modified the `stream` method to be able to receive a function under parameter `monitor` that wraps around the thread call, then I can pass the function when needed.  My actual code is somewhat different to also support this change: https://github.com/thisbejim/Pyrebase/pull/150. But the change should be something like this:

```
from pyrebase import pyrebase as pyrebase_internals


class CustomStream(pyrebase_internals.Stream):
    def __init__(self, url, stream_handler, build_headers, stream_id, monitor):
        self.monitor = monitor
        super().__init__(url, stream_handler, build_headers, stream_id)

    def start_stream(self):
        if self.monitor and callable(self.monitor):
            self.monitor(super().start_stream)
        else:
            super().start_stream()


class CustomDatabase(pyrebase_internals.Database):
    def stream(self, stream_handler, token=None, stream_id=None, monitor=None):
        request_ref = self.build_request_url(token)
        return CustomStream(request_ref, stream_handler, self.build_headers, stream_id, monitor)


class CustomFirebase(pyrebase_internals.Firebase):
    def database(self):
        return CustomDatabase(self.credentials, self.api_key, self.database_url, self.requests)


def custom_initialize_app(config):
    return CustomFirebase(config)

firebase = custom_initialize_app(FIREBASE_CONFIG)
```

And to initialize a stream:

```
from firebase import firebase

db = firebase.database()

def monitor_stream_of_events():
    try:
        return continue_stream()
    except Exception:
        client.captureException(tags={'handled_status': 'catched_and_logged'})

monitored_stream = db.child("<child_to_stream>").stream(stream_handler=stream_handler, monitor=monitor_stream_of_events)
```

The only purpose of this is to log exceptions, the actual restarting is done checking the threads. Hope you can follow up here :+1:

**Comment by mcarrilloco** [comment]
After thinking on this issue I think the best option for the library is to provide a synchronous stream (an option to not start a new thread) and give developers the option to handle the concurrency themselves. Seems like a fairly simple change and will give full customization options to people building solutions on top of the library. Thanks again for this useful library! Hope my input can be useful to the project.

**Comment by thisbejim** [comment]
That is so true @mcarrilloco, I don't even remember why it starts in a new thread, I think I may have copied that from some official firebase example somewhere. It is a bit of breaking change though to remove it, would be good to hear input from others about this.
