### ISSUE TITLE
'requests.exceptions.ConnectionError' when uploading file to storage

### ISSUE THREAD

**Issue by BRoy98** [thisbejim/Pyrebase#154]
[✓] Check that your version of Python is 3.4+
[✓] Check that you are on the newest version of Pyrebase
[✓] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

### I am getting this error when I am trying to uplaod a file to my firebase storage.

```
File "upload.py", line 152, in uploadDatabase
    storage.child("weather.db").put("weather.db")
  File "/usr/local/lib/python2.7/dist-packages/pyrebase/pyrebase.py", line 405, in put
    request_object = self.requests.post(request_ref, data=file_object)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='firebasestorage.googleapis.com', port=443): Max retries exceeded with url: /v0/b/[firebase_url_here].appspot.com/o?name=weather.db (Caused by ProtocolError('Connection aborted.', BadStatusLine("''",)))

```

I tried this also but got same error:
`storage.put("weather.db")`

**Comment by thisbejim** [comment]
Hi @BRoy98, thanks for dropping by!

I can see that you are using python2, Pyrebase only supports python3 which is why you are getting this error.

**Comment by BRoy98** [comment]
Hi @thisbejim, I tried with python3 and got this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='firebasestorage.googleapis.com', port=443): Max retries exceeded with url: /v0/b/[firebase_url_here].appspot.com/o?name=None (Caused by ProtocolError('Connection aborted.', BadStatusLine("''",)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upload.py", line 345, in <module>
    run()
  File "upload.py", line 309, in run
    copyToCloud()
  File "upload.py", line 288, in copyToCloud
    storage.put("weather.db")
  File "/usr/local/lib/python3.4/dist-packages/pyrebase/pyrebase.py", line 405, in put
    request_object = self.requests.post(request_ref, data=file_object)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='firebasestorage.googleapis.com', port=443): Max retries exceeded with url: /v0/b/[firebase_url_here].appspot.com/o?name=None (Caused by ProtocolError('Connection aborted.', BadStatusLine("''",)))
```

**Comment by z404** [comment]
Hi @thisbejim , i get a similar problem while using the stream listener to listen to changes without an internet connection. I want to know how to be able to catch this error, and on which line of code do i put my try except block on. I have tried catching the error on this line
```
try:
    my_stream = db.child('user_database').stream(stream_handler)
except ConnectionError:
    print('Connection Error')
```
and on my entire code, but the error doesn't get caught.

**Comment by beaconIOT** [comment]
Hey @z404  and @thisbejim did you find a solution to this? Right now if I lose internet connection on my rpi running Pyrebase in python it just grinds my code to a halt. Any help would be amazing!
