### ISSUE TITLE
pip install fails on windows 10, python 3.6.1

### ISSUE THREAD

**Issue by robianmcd** [thisbejim/Pyrebase#179]
Any idea why I get the following error when I run `pip install pyrebase`

```
C:\Users\Rob> pip install pyrebase
Collecting pyrebase
  Using cached Pyrebase-3.0.27-py3-none-any.whl
Collecting oauth2client==3.0.0 (from pyrebase)
  Using cached oauth2client-3.0.0.tar.gz
Collecting python-jwt==2.0.1 (from pyrebase)
  Using cached python_jwt-2.0.1-py2.py3-none-any.whl
Collecting requests==2.11.1 (from pyrebase)
  Using cached requests-2.11.1-py2.py3-none-any.whl
Collecting gcloud==0.17.0 (from pyrebase)
  Using cached gcloud-0.17.0.tar.gz
Collecting pycryptodome==3.4.3 (from pyrebase)
  Using cached pycryptodome-3.4.3-cp36-cp36m-win32.whl
Collecting requests-toolbelt==0.7.0 (from pyrebase)
  Using cached requests_toolbelt-0.7.0-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client==3.0.0->pyrebase)
  Using cached httplib2-0.10.3.tar.gz
Requirement already satisfied: pyasn1>=0.1.7 in c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages (from oauth2client==3.0.0->pyrebase)
Requirement already satisfied: pyasn1-modules>=0.0.5 in c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages (from oauth2client==3.0.0->pyrebase)
Requirement already satisfied: rsa>=3.1.4 in c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages (from oauth2client==3.0.0->pyrebase)
Requirement already satisfied: six>=1.6.1 in c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages (from oauth2client==3.0.0->pyrebase)
Collecting jws>=0.1.3 (from python-jwt==2.0.1->pyrebase)
  Using cached jws-0.1.3.tar.gz
Collecting googleapis-common-protos (from gcloud==0.17.0->pyrebase)
  Using cached googleapis-common-protos-1.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
        @_call_aside
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "c:\users\rob\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Rob\AppData\Local\Temp\pip-build-4bey7m5c\googleapis-common-protos\
```

I'm running:
Windows 10
Python 3.6.1
pip 9.0.1

Thanks

**Comment by robianmcd** [comment]
Nevermind. I ran `pip install --upgrade setuptools` and that fixed the issue

**Comment by blotfi** [comment]
pip install --upgrade setuptools
didn't solve my issue

I am still having an error, on Windows10, python 3.7:

Installing collected packages: pycryptodome, pyrebase
  Running setup.py install for pycryptodome ... error
    Complete output from command "C:\Program Files\Python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\...\\AppData\\Local\\Temp\\pip-install-a9kop2nb\\pycryptodome\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\...\AppData\Local\Temp\pip-record-dm88ctzw\install-record.txt --single-version-externally-managed --compile:

**Comment by kj666** [comment]
I have had same issue. I just ended up using python 3.6 in a virtual environment

**Comment by ghost** [comment]
pip3 install pyrebase4

**Comment by SuyogAdhikari** [comment]
> 
> 
> pip3 install pyrebase4

This worked for me....

**Comment by Melvin231** [comment]
Thanks
