### ISSUE TITLE
SSEClient Auth Fails in Streaming 

### ISSUE THREAD

**Issue by johnsonc** [thisbejim/Pyrebase#197]
Hello, 

Intermittent outages in streaming keep happening. More often than not, the same error pops up.

SSECClient seems to fail. 

I've tried to monkey-patch the library as mentioned here [1], [2] but to no avail, 

I was poking in the codebase to figure this out, but I'm hitting dead ends. 

Anybody have insight on this?

Stack trace: 

/home/johnson/repos/blu/FireFlask/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/johnson/repos/blu/FireFlask/venv/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 557, in start_stream
    for msg in self.sse:
  File "/home/johnson/repos/blu/FireFlask/venv/local/lib/python2.7/site-packages/sseclient/sseclient.py", line 85, in __next__
    self._connect()
  File "/home/johnson/repos/blu/FireFlask/venv/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 522, in _connect
    super(ClosableSSEClient, self)._connect()
  File "/home/johnson/repos/blu/FireFlask/venv/local/lib/python2.7/site-packages/sseclient/sseclient.py", line 54, in _connect
    self.resp.raise_for_status()
  File "/home/johnson/repos/blu/FireFlask/venv/local/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized for url: https://sasdea65f.firebaseio.com/test/threads.json

References: 
1: https://github.com/thisbejim/Pyrebase/issues/117
2: https://github.com/thisbejim/Pyrebase/issues/143

**Comment by thisbejim** [comment]
Hi there! Pyrebase does not support python2 as mentioned in the README, please switch to python3.

**Comment by johnsonc** [comment]
Oh, I overlooked that.. Sorry!

This is with 3.4 and the latest code from master. 


Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/Pyrebase-3.0.27-py3.4.egg/pyrebase/pyrebase.py", line 557, in start_stream
    for msg in self.sse:
  File "/usr/local/lib/python3.4/dist-packages/Pyrebase-3.0.27-py3.4.egg/sseclient/sseclient.py", line 85, in __next__
    self._connect()
  File "/usr/local/lib/python3.4/dist-packages/Pyrebase-3.0.27-py3.4.egg/pyrebase/pyrebase.py", line 522, in _connect
    super(ClosableSSEClient, self)._connect()
  File "/usr/local/lib/python3.4/dist-packages/Pyrebase-3.0.27-py3.4.egg/sseclient/sseclient.py", line 54, in _connect
    self.resp.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests-2.11.1-py3.4.egg/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://bluback-ea65f.firebaseio.com/test/threads.json
