### ISSUE TITLE
create custom token is fall, check it please!!

### ISSUE THREAD

**Issue by hikarikagayaku** [thisbejim/Pyrebase#208]
auth = firebase.auth()
uid = "...."
token = auth.create_custom_token(uid)
user = auth.sign_in_with_custom_token(token)

it not working, hope you a lot of time to check it. thankyou

Traceback (most recent call last):
  File "/home/pi/Desktop/test.py", line 19, in <module>
    token = auth.create_custom_token(uid)
  File "/usr/local/lib/python3.5/dist-packages/pyrebase/pyrebase.py", line 90, in create_custom_token
    service_account_email = self.credentials.service_account_email
AttributeError: 'NoneType' object has no attribute 'service_account_email'

**Comment by brandonmichaelhunter** [comment]
@thisbejim - Here's what I've found on the firebase site that might relate to this error:
"Custom token creation works only when the SDK is authenticated with a service account (certificate) credential.'

Ref: https://firebase.google.com/docs/auth/admin/create-custom-tokens

Based on this, we should update the documentation to add a service account to config object first using the sign_in_with_custom_token(token) method.

Just a thought :)

**Comment by brandonmichaelhunter** [comment]
I just confirmed, a service account is needed and should be added to the config object if you're going to use the sign_in_with_custom_token(token) method.

**Comment by hikarikagayaku** [comment]
Thank you for reply. I'm newbie in the development. I will try do it. Thank you

**Comment by brandonmichaelhunter** [comment]
No problem. Let us know if this worked. Thanks

@thisbejim  - we should probably add a comment in your documentation about using a service account if you're using the sign_in_with_custom_token() method. I can update the page if you want me too. Let me know. Thanks

**Comment by mak3rm1k3** [comment]
Hey this is an awesome library with great functionality. I have a service account and am trying custom tokens. With:

token = auth.create_custom_token(uid)
user = auth.sign_in_with_custom_token(token)

I get 500 response for an internal server error within firebase. Firebase documentation looks consistent with the pyrebase's request, anyone know where the error might be coming from?

**Comment by tgrzinic** [comment]
> Hey this is an awesome library with great functionality. I have a service account and am trying custom tokens. With:
> 
> token = auth.create_custom_token(uid)
> user = auth.sign_in_with_custom_token(token)
> 
> I get 500 response for an internal server error within firebase. Firebase documentation looks consistent with the pyrebase's request, anyone know where the error might be coming from?

Same problem with my sign in with custom token, have you managed to find a workaround?

**Comment by mak3rm1k3** [comment]
Sorry @tgrzinic I didn't get this working

**Comment by tgrzinic** [comment]
As a workaround I check the token with  jwt.decode (https://python-jose.readthedocs.io/en/latest/jwt/api.html) if it is valid.
