### ISSUE TITLE
Error when closing stream

### ISSUE THREAD

**Issue by vmanikes** [thisbejim/Pyrebase#246]
Make sure these boxes are checked before submitting your issue:

[Yep] Check that your version of Python is 3.4+
[Yep] Check that you are on the newest version of Pyrebase
[Yep] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

Here is my error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/RaspberryPI-Prototype/routes/transaction/transaction.py", line 76, in create_transaction
    my_stream.close()
  File "/usr/local/lib/python3.5/dist-packages/pyrebase/pyrebase.py", line 569, in close
    self.sse.close()
  File "/usr/local/lib/python3.5/dist-packages/pyrebase/pyrebase.py", line 530, in close
    self.resp.raw._fp.fp.raw._sock.close()
AttributeError: 'NoneType' object has no attribute 'raw'

**Comment by vmanikes** [comment]
Issue number #205 solved my problem when I changed the source code of pyrebase. Someone update this changes to upstream
