### ISSUE TITLE
AttributeError when referencing database

### ISSUE THREAD

**Issue by DannyDannyDanny** [thisbejim/Pyrebase#258]
### Prerequisites
* Python 3.6.5
* Downloaded Pyrebase this morning
* Email/password sign in method enabled

### My Code

I'm just trying to get firebase <-> python to talk.

```python
import pyrebase

# I've temporarily deleted the credentials
config = dict()
email = "eml@dmn.com"
password = "password"

firebase = pyrebase.initialize_app(config)
auth = firebase.auth()
user = auth.sign_in_with_email_and_password(email, password)

# Next line is where shit hits the fan and also line 21 in my real script
db = firebase.database()

# I dont know if this will run
db.child("users").child("Morty")
print("nice")
```

### The error I receive

```
Traceback (most recent call last):
  File "python/firebase/firebasecon.py", line 21, in <module>
    db = firebase.database()
  File "/usr/local/lib/python3.6/site-packages/pyrebase/pyrebase.py", line 66, in database
    return Database(self.credentials, self.api_key, self.database_url, self.requests)
  File "/usr/local/lib/python3.6/site-packages/pyrebase/pyrebase.py", line 171, in __init__
    if not database_url.endswith('/'):
AttributeError: 'tuple' object has no attribute 'endswith'
```

Guidance is appreciated 😽

Thank you for helping make Pyrebase better!

**Comment by DannyDannyDanny** [comment]
@zachyam Nope. I have a feeling this repo is no longer maintained. This did reignite my interest in connecting python to firebase again and I'm watching google's [firecast tutorial for python](https://www.youtube.com/watch?v=yylnC3dr_no).

**Comment by URSORATHI** [comment]
@DannyDannyDanny which python library did you use? The link you have provided gives an error.

**Comment by DannyDannyDanny** [comment]
Link dead. Code gone.

**Comment by ghost** [comment]
is there still any solution for this?
