### ISSUE TITLE
Getting a googleapis-common-protos error while installing Pyrebase using pip

### ISSUE THREAD

**Issue by MarbilleJuntado** [thisbejim/Pyrebase#259]
The stack trace: 
```Installing collected packages: httplib2, pyasn1, pyasn1-modules, rsa, oauth2client, requests, protobuf, googleapis-common-protos, gcloud, requests-toolbelt, jws, python-jwt, pycryptodome, pyrebase
  Running setup.py install for httplib2 ... done
  Running setup.py install for oauth2client ... done
  Found existing installation: requests 2.18.1
    Uninstalling requests-2.18.1:
      Successfully uninstalled requests-2.18.1
  Running setup.py install for googleapis-common-protos ... error
    Complete output from command /home/jmcabrera/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7m_5yu81/googleapis-common-protos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_i_t4rsj-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jmcabrera/venv/include/site/python3.6/googleapis-common-protos:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/jmcabrera/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "/home/jmcabrera/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7m_5yu81/googleapis-common-protos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_i_t4rsj-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jmcabrera/venv/include/site/python3.6/googleapis-common-protos" failed with error code 1 in /tmp/pip-build-7m_5yu81/googleapis-common-protos/```

Also, why did it uninstall `requests-2.18.1`?

**Comment by jrizzoli** [comment]
Me too

**Comment by ijami** [comment]
Me too!
