### ISSUE TITLE
getting AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by aditsrivastava4** [thisbejim/Pyrebase#261]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cffi/cparser.py", line 5, in <module>
    from . import _pycparser as pycparser
ImportError: cannot import name '_pycparser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adit/fbStorage.py", line 1, in <module>
    import pyrebase
  File "/usr/local/lib/python3.6/dist-packages/pyrebase/__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "/usr/local/lib/python3.6/dist-packages/pyrebase/pyrebase.py", line 17, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
  File "/usr/local/lib/python3.6/dist-packages/oauth2client/service_account.py", line 25, in <module>
    from oauth2client import client
  File "/usr/local/lib/python3.6/dist-packages/oauth2client/client.py", line 47, in <module>
    from oauth2client import crypt
  File "/usr/local/lib/python3.6/dist-packages/oauth2client/crypt.py", line 55, in <module>
    from oauth2client import _pycrypto_crypt
  File "/usr/local/lib/python3.6/dist-packages/oauth2client/_pycrypto_crypt.py", line 16, in <module>
    from Crypto.Hash import SHA256
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Hash/SHA256.py", line 39, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Util/_raw_api.py", line 39, in <module>
    ffi = FFI()
  File "/usr/local/lib/python3.6/dist-packages/cffi/api.py", line 63, in __init__
    from . import cparser
  File "/usr/local/lib/python3.6/dist-packages/cffi/cparser.py", line 7, in <module>
    import pycparser
  File "/usr/local/lib/python3.6/dist-packages/pycparser/__init__.py", line 14, in <module>
    from .c_parser import CParser
  File "/usr/local/lib/python3.6/dist-packages/pycparser/c_parser.py", line 20, in <module>
    class CParser(PLYParser):
  File "/usr/local/lib/python3.6/dist-packages/pycparser/plyparser.py", line 95, in template
    _create_param_rules(cls, method)
  File "/usr/local/lib/python3.6/dist-packages/pycparser/plyparser.py", line 112, in _create_param_rules
    param_rule.__doc__ = func.__doc__.replace('xxx', xxx).replace('yyy', yyy)
AttributeError: 'NoneType' object has no attribute 'replace'
```

i m getting `AttributeError` on `import pyrebase` i searched the solution for this issue and did not find any
so can anyone tell me y i m seeing this
 

```
import pyrebase
print('pyrebase')

config = {
  "apiKey": "apiKey",
  "authDomain": "projectId.firebaseapp.com",
  "databaseURL": "https://databaseName.firebaseio.com",
  "storageBucket": "projectId.appspot.com"
}
firebase = pyrebase.initialize_app(config)
```

**Comment by swapnadeepmohapatra** [comment]
pip install --upgrade pyasn1-modules

or 

pip install --upgrade google-auth-oauthlib
