### ISSUE TITLE
404 Not Found Error Message When Using get() Method

### ISSUE THREAD

**Issue by c-gallagher1993** [thisbejim/Pyrebase#262]
I'll preface this by saying that I'm new to coding with Python/pyrebase, so I apologize if this error is just a result of my ignorance...

I'm trying to retrieve data from my Firebase database using the get() method. I've set up my configuration and have created user information for myself, and it all seems to be working as the shell recognizes I have a pyrebase.Database object (see Code below). However, when I try to use the get() method, I start receiving "404 Not Found" error messages (see Error Message below). I'm not sure if there is an issue with my code, with how I've set up python/pyrebase, or with the backend of my Firebase, but I'd appreciate any insights you can give me on why I'm receiving these errors.

### Code
```
firebase = pyrebase.initialize_app(config)

#Get a reference to the auth service
auth = firebase.auth()

#Log the User in
user = auth.sign_in_with_email_and_password("email", "password")
#Refresh token
user = auth.refresh(user['refreshToken'])
userIdToken = user['idToken']

#Get a reference to the database service
db = firebase.database()
raw_data = db.child("todoItems").get()
```

### Error Message
```
Traceback (most recent call last):
  File "C:\Users\Conor\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrebase\pyrebase.py", line 444, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\Conor\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://databaseName.firebaseio.com/todoItems.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Conor\Dropbox (MFO)\AA_Projects\Garment Worker Diaries\Phase_2\New folder\Firebase_testing.py", line 21, in <module>
    raw_data = db.child("todoItems").get()
  File "C:\Users\Conor\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrebase\pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "C:\Users\Conor\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 404 Client Error: Not Found for url: https://databaseName.firebaseio.com/todoItems.json] {
  "error" : "404 Not Found"
```

Make sure these boxes are checked before submitting your issue:

[X] Check that your version of Python is 3.4+
[X] Check that you are on the newest version of Pyrebase
[X] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

**Comment by hazelf42** [comment]
I am also having this issue. It adds .json to the ends of URLs, which I think is causing the problem. No solution found.

**Comment by harrisbegca** [comment]
Same... has anyone come to a solution since then?
