### ISSUE TITLE
Fails install with error code 1

### ISSUE THREAD

**Issue by benny123tw** [thisbejim/Pyrebase#288]
run `pip install Pyrebase` and get the following error.

```
Collecting pyrebase
  Using cached https://files.pythonhosted.org/packages/4e/1f/86ec68bfe0d6ffeadbab2ab0651ddf1c7206a0c4421b39baeb69b3a9c5cd/Pyrebase-3.0.27-py3-none-any.whl
Collecting requests==2.11.1 (from pyrebase)
  Using cached https://files.pythonhosted.org/packages/ea/03/92d3278bf8287c5caa07dbd9ea139027d5a3592b0f4d14abf072f890fab2/requests-2.11.1-py2.py3-none-any.whl
Collecting python-jwt==2.0.1 (from pyrebase)
  Using cached https://files.pythonhosted.org/packages/dd/2a/9c4230b09f63737e7beb34e3a19895cd50c5ff88af16d3cd54cd71e2325a/python_jwt-2.0.1-py2.py3-none-any.whl
Collecting gcloud==0.17.0 (from pyrebase)
  Using cached https://files.pythonhosted.org/packages/0f/9d/56ecba02b4c117a43a906098095bccaea94d3edf57cb407c071efd87002f/gcloud-0.17.0.tar.gz
Collecting pycryptodome==3.4.3 (from pyrebase)
  Using cached https://files.pythonhosted.org/packages/45/ef/4514a01be3d8f5383cd12fc5612ffd8a2508ac7e7ff6bde2da708e71c9a3/pycryptodome-3.4.3.tar.gz
Collecting oauth2client==3.0.0 (from pyrebase)
  Using cached https://files.pythonhosted.org/packages/c0/7b/bc893e35d6ca46a72faa4b9eaac25c687ce60e1fbe978993fe2de1b0ff0d/oauth2client-3.0.0.tar.gz
Collecting requests-toolbelt==0.7.0 (from pyrebase)
  Using cached https://files.pythonhosted.org/packages/57/60/cc85ca45c85585191e70e21687aeaa74ec4e555a1404628ba77b8af7d92e/requests_toolbelt-0.7.0-py2.py3-none-any.whl
Collecting jws>=0.1.3 (from python-jwt==2.0.1->pyrebase)
  Using cached https://files.pythonhosted.org/packages/01/9e/1536d578ed50f5fe8196310ddcc921a3cd8e973312d60ac74488b805d395/jws-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\BennyYen\AppData\Local\Temp\pip-install-1ed3orbi\jws\setup.py", line 17, in <module>
        long_description=read('README.md'),
      File "C:\Users\BennyYen\AppData\Local\Temp\pip-install-1ed3orbi\jws\setup.py", line 5, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 500: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\BY\AppData\Local\Temp\pip-install-1ed3orbi\jws\
```

- Windows 10
- Python 3.7
- pip 18.1

I'm already installed up-to-date setuptools. (40.6.2)

**Comment by Rumidom** [comment]
i was having problems installing Pyrebase from pip as well, you could try installing PR 246 from source, this worked for me:
0 - open git bash anywhere 
1 - clone the repository: `git clone https://github.com/thisbejim/Pyrebase.git`
2 - inside the folder you just cloned use: `git fetch origin pull/249/head:upgrade-google-auth` 
3 - then use: `git checkout upgrade-google-auth`
4 - now you can install Pyrebase using CMD inside Pyrebases folder `python setup.py install --user`

**Comment by benny123tw** [comment]
@Rumidom Thanks! it works!!

**Comment by fahaad-abbadi** [comment]
Thank you very much!

**Comment by arduino-monkey** [comment]
thanks! it works like a charm
