### ISSUE TITLE
Pyrebase into IronPython

### ISSUE THREAD

**Issue by ivanko337** [thisbejim/Pyrebase#293]
I tried to install Pyrebase into IronPython via pip (ipy32.exe -X:Frames -m pip install pyrebae).

An error occurred during the installation: 
Collecting googleapis-common-protos (from gcloud==0.17.0->pyrebase)
  Using cached https://files.pythonhosted.org/packages/61/29/1549f61917eadd11650e42b78b4afcfe9cb467157af4510ab8cb59535f14/googleapis-common-protos-1.5.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\setuptools\__init__.py", line 11, in <module>
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 2908, in <module>
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 2913, in _call_aside
      File "C:\Program Files\IronPython 2.7\Lib\pkgutil.py", line 243, in load_module
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 2952, in _initialize_master_working_set
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 956, in subscribe
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 2952, in <lambda$106>
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 2515, in activate
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 2097, in declare_namespace
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 2046, in _handle_ns
    ImportError: no module named google

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\public\documents\wondershare\creatortemp\pip-build-le70yk\googleapis-common-protos\

I tried to install the google module manually and tried to install pyrebase again, but the same error was repeated.
What should I do?

I use IronPython2.7, Windows 10 and Pyrebase 3.0.27.

**Comment by FavPoint** [comment]
`pip install google`

Installs the google package
