### ISSUE TITLE
Pyrebase "hangs" while retrieving val from db

### ISSUE THREAD

**Issue by Giancrafter** [thisbejim/Pyrebase#316]
Previously, when I used pyrebase it just worked fine. But now, 1 week later with the same python file there is just no reaction. It just doesnt anything until I press Ctrl+C. Then it Shows this error Code:
`Traceback (most recent call last):
  File "Read.py", line 100, in <module>
    dbname = db.child("users").order_by_child("nfc").equal_to(user).get()
  File "/usr/local/lib/python3.7/dist-packages/pyrebase/pyrebase.py", line 261, in get
    headers = self.build_headers(token)
  File "/usr/local/lib/python3.7/dist-packages/pyrebase/pyrebase.py", line 252, in build_headers
    access_token = self.credentials.get_access_token().access_token
  File "/usr/local/lib/python3.7/dist-packages/oauth2client/client.py", line 677, in get_access_token
    self.refresh(http)
  File "/usr/local/lib/python3.7/dist-packages/oauth2client/client.py", line 560, in refresh
    self._refresh(http.request)
  File "/usr/local/lib/python3.7/dist-packages/oauth2client/client.py", line 765, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/local/lib/python3.7/dist-packages/oauth2client/client.py", line 797, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/usr/local/lib/python3.7/dist-packages/httplib2/__init__.py", line 1953, in request
    cachekey,
  File "/usr/local/lib/python3.7/dist-packages/httplib2/__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python3.7/dist-packages/httplib2/__init__.py", line 1524, in _conn_request
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/httplib2/__init__.py", line 1305, in connect
    sock.connect((self.host, self.port))
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Read.py", line 112, in <module>
    sleep(5)
KeyboardInterrupt
`
Please help me soon.

**Comment by idrishmakda52** [comment]
whats your python version please tell me because I am done installing pyrebse but can't import and use it

**Comment by Giancrafter** [comment]
I've got the same problem on other Computer.
Did you try using install with "git clone"?
