### ISSUE TITLE
Error missing files

### ISSUE THREAD

**Issue by dipalmabiagio** [thisbejim/Pyrebase#342]
Hi there,

I get this error when i try to use auth.sign_in_with_email_and_password(email, password) function.

The code that triggers the exception is:

  ```
    print (config)
    firebase = pyrebase.initialize_app(config)
    print(firebase)
    auth = firebase.auth()
    user = auth.sign_in_with_email_and_password(email, password)
    print("user in firebase_connection function:\n")
    print(user)
    return True, user
```

My environment is:

- python 3.6
- need to use pyinstaller to export software
- all required package are installed

The details of the errors are below:

```
Traceback (most recent call last):
  File "requests/packages/urllib3/util/ssl_.py", line 295, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 423, in send
  File "requests/packages/urllib3/connectionpool.py", line 595, in urlopen
  File "requests/packages/urllib3/connectionpool.py", line 352, in _make_request
  File "requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
  File "requests/packages/urllib3/connection.py", line 289, in connect
  File "requests/packages/urllib3/util/ssl_.py", line 297, in ssl_wrap_socket
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "login.py", line 65, in login
  File "firebase_connections.py", line 141, in login_firebase
  File "pyrebase/pyrebase.py", line 84, in sign_in_with_email_and_password
  File "requests/api.py", line 110, in post
  File "requests/api.py", line 56, in request
  File "requests/sessions.py", line 475, in request
  File "requests/sessions.py", line 596, in send
  File "requests/adapters.py", line 497, in send
requests.exceptions.SSLError: [Errno 2] No such file or directory
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by dipalmabiagio** [comment]
After some issues I found out that this library is not compatible with PyInstaller, in my opinion. Switch to another client library fixed the issue.
