### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Ad0rableTrooper** [thisbejim/Pyrebase#384]
I have an issue regarding installing pyrebase.

```
ERROR: Command errored out with exit status 1: 'c:\users\monda\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\monda\\AppData\\Local\\Temp\\pip-install-t3pm31_2\\pycryptodome_0aa27e226fd4441b811fbe091eda8877\\setup.py'"'"'; __file__='"'"'C:\\Users\\monda\\AppData\\Local\\Temp\\pip-install-t3pm31_2\\pycryptodome_0aa27e226fd4441b811fbe091eda8877\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\monda\AppData\Local\Temp\pip-record-jujdvdkw\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\monda\appdata\local\programs\python\python39\Include\pycryptodome' Check the logs for full command output.
```
Please help me in this issue.

One more thing is that, I have tried to use pyrebase4 and pyrebase5 but there is an error which says

```
Traceback (most recent call last):
  File "C:\Users\monda\Desktop\RM Schools Admin Login Page Directory\databaseconn.py", line 1, in <module>
    import pyrebase
  File "C:\Users\monda\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrebase\__init__.py", line 1, in <module> 
    from .pyrebase import initialize_app
  File "C:\Users\monda\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrebase\pyrebase.py", line 23, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by TharushaT** [comment]
Try to install `pycryptodome` separately using this command. Make sure to run the terminal as administrator.

**`pip install pycryptodome`**

Then Install:

**`pip install pyrebase4`**

**Comment by Ad0rableTrooper** [comment]
Thanks for your reply @TharushaT, I have figured out a solution on my own. I install pyrebase on a virtual environment and it works on every system.
