### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by hamdivazim-archive** [thisbejim/Pyrebase#450]
On import this exception is raised:
```
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by hamdivazim-archive** [comment]
Full exception:
```
Traceback (most recent call last):
  File "/[LOCATION]/venv/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/[LOCATION]/venv/lib/python3.10/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/[LOCATION]/venv/lib/python3.10/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/[LOCATION]/venv/lib/python3.10/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/[LOCATION]/venv/lib/python3.10/site-packages/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/[LOCATION]/venv/lib/python3.10/si
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import pyrebase
  File "/[LOCATION]/venv/lib/python3.10/site-packages/pyrebase/__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "/[LOCATION]/venv/lib/python3.10/site-packages/pyrebase/pyrebase.py", line 1, in <module>
    import requests
  File "/[LOCATION]/venv/lib/python3.10/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/[LOCATION]venv/lib/python3.10/site-packages/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "[LOCATION]/venv/lib/python3.10/site-packages/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

[LOCATION] is the location of the code.

**Comment by hamdivazim-archive** [comment]
Turns out it is a compatibility issue (I was using py3.10)

**Comment by AsifArmanRahman** [comment]
[firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api) for python3.6 to python3.11.

**Comment by hamdivazim-archive** [comment]
Thanks, just discovered your project - looks great!

**Comment by Tato418** [comment]
Not working even-tough using python 3.10
Python 3.10.12 (main, Nov 20 2023, 15:14:05)

**Comment by Express-Ai** [comment]
@AsifArmanRahman need to add `self.storage_bucket = config["storageBucket"]` to Firebase.__init__

**Comment by baksh97** [comment]
@AsifArmanRahman need to add `self.storage_bucket = config["storageBucket"]` to Firebase.__init__
Storage won't work without it
