### ISSUE TITLE
Issue getting started

### ISSUE THREAD

**Issue by andybraxton** [thisbejim/Pyrebase#77]
Hi there,

I've run into an issue when trying to get started with Pyrebase. I get the following error:

Traceback (most recent call last):
  File "test2.py", line 14, in <module>
    import pyrebase
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyrebase/__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 19, in <module>
    from requests.packages.urllib3.contrib.appengine import is_appengine_sandbox
ImportError: No module named appengine

in terminal in OSX when trying to run my python script with Pyrebase in it.

Any ideas why this might be?

I have separately installed and set up Google Cloud SDK on my machine.

Andy

**Comment by thisbejim** [comment]
Hi @andybraxton, I hope you are doing well.

I believe this error is because Pyrebase does not work with python2, you will have to use python3.
