### ISSUE TITLE
pip3 install Unicode decode error in Docker container

### ISSUE THREAD

**Issue by sEpt0r** [thisbejim/Pyrebase#87]
I have the same issue as #82
I can't install pyrebase in docker container with python 3.5.

The simplest Dockerfile for test it:

```
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y python3-pip

RUN pip3 install Pyrebase
```

```
Collecting jws>=0.1.3 (from python-jwt->Pyrebase->-r /app/requirements.txt (line 5))
  Downloading jws-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-r4gg1082/jws/setup.py", line 17, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-build-r4gg1082/jws/setup.py", line 5, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 500: ordinal not in range(128)
```

I installed fixed jws from source and Pyrebase was successfully installed.
Some guys recommend install PyJWT instead python-jwt, also https://jwt.io/ recommends to install PyJWT. 
Do you have a plans to migrate from python-jwt on PyJWT?

**Comment by thisbejim** [comment]
Hi @sEpt0r, thanks for bringing this up! This should be fixed by https://github.com/thisbejim/Pyrebase/pull/93, please let me know if you find that this error still exists on your end. If it does we will move to PyJWT.

**Comment by TobiasMR** [comment]
Hi @thisbejim, thanks for the comment. I am still experiencing this issue after you merged the commit in #93.

```
Collecting jws>=0.1.3 (from python-jwt==2.0.1->pyrebase)
  Downloading jws-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fmrf4cra/jws/setup.py", line 17, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-build-fmrf4cra/jws/setup.py", line 5, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/opt/conda/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 500: ordinal not in range(128)
```

I used the same Dockerfile as @sEpt0r to test it.

**Comment by ukjin1192** [comment]
First of all, thanks for this great project 👍 

I have same issue - From version `3.0.12`, it failed with `UnicodeDecodeError`.

In case of version `3.0.11`, it does not yield `UnicodeDecodeError`, but dependency error occurred from `six`, `packaging` and `appdirs`. I succeed to install after installing these packages.

**Comment by mcarrilloco** [comment]
Seems like the problems here come from the dependency `jws`. I am also experiencing this issue when installing in a VPS with Ubuntu. There are two open pull request right now that seems to solve the issue but haven't been merged into the dependency:

https://github.com/brianloveswords/python-jws/pull/25
https://github.com/brianloveswords/python-jws/pull/21

**Comment by ippeiukai** [comment]
Following work around did the job:
`LC_CTYPE="en_US.UTF-8" pip install jws`

**Comment by alex1989** [comment]
you could try this before install pip dependecies, it should helps you
```
ENV LANG C.UTF-8
```

**Comment by DmitryAlekseev** [comment]
it's work for me

export LANG=C.UTF-8
pip install pyrebase

**Comment by hpbl** [comment]
As @DmitryAlekseev suggested, adding `ENV LANG C.UTF-8` to my Dockerfile solved the problem.
